{globals.i}

DEF INPUT PARAM iAcct AS CHAR NO-UNDO.

DO ON ERROR UNDO, RETRY:

DEFINE VARIABLE m31F AS CHARACTER  NO-UNDO.
DEFINE VARIABLE m31Fk AS CHARACTER  NO-UNDO.
DEFINE VARIABLE i AS INTEGER  INIT 1000  NO-UNDO. 
DEFINE VARIABLE mAcct LIKE acct.acct  NO-UNDO.
DEFINE VARIABLE mCopy AS LOGICAL    NO-UNDO.
DEFINE VARIABLE mFil AS CHARACTER  NO-UNDO.



FOR EACH acct  
    WHERE acct.acct EQ iAcct NO-LOCK:


OUTPUT TO VALUE("./100hab" + TRIM(ENTRY(1,iAcct,"@")) + ".tel").

m31F = REPLACE(SUBSTR(ISO-DATE(MAX(acct.open-date,DATE("01.01.2016"))),3),"-","").

m31Fk = REPLACE(SUBSTR(ISO-DATE(TODAY),3),"-","").

PUT UNFORMATTED
"YZYZ" SKIP(2)
"FROM:iBank2" SKIP
"TO:Bisquit" SKIP
"DATE:" + SUBSTRING(STRING(YEAR(TODAY), "9999"), 3, 2) + STRING(MONTH(TODAY), "99") + STRING(DAY(TODAY), "99") SKIP
"TIME:" + TRIM(STRING(TIME, ">>>>>>>9")) SKIP " " SKIP
"::920 ‡€‘  ‘‘’Ÿˆˆ ‘—…’€" SKIP " " SKIP
":20:1344493890720" SKIP
":12:940" SKIP
":25:" + SUBSTR(acct.acct, 1, 20)  SKIP
":31F:" + m31F + "/" + m31Fk SKIP " " SKIP
"NNNN" SKIP.
OUTPUT CLOSE.

OS-COMMAND VALUE("mv ./*.tel /home2/bis/quit41d/imp-exp/" + acct.Filial-id + "/bss/in").

END.

END.




