[Setting] // Экспорт данных произвел GSBIS 31/08/2015 12:08:24 БД "-db /home2/bis/quit41d/db-spb/bisquit,-ld bisquit,-Mm 16384,-spin 5000"
"base" "СтандТр" "Параметры настройки стандартных транзакций" "" "C" "" "" "" yes yes ""
"base" "СтандТр" "Ведение Картотеки 2 в разрезе клиента/счета" "НЕТ" "l" "ДА/НЕТ" "К2ПоКл" "" yes no "Касается только открытия счетов 90902. Если НП имеет значение ""ДА"", то работает старый алгоритм открытия/поиска счета 90902 (К2 ведется по клиенту, где на единый 90902 ставятся документы с разных расчетных счетов клиента).  Если же НП имеет значение ""НЕТ"", то внебалансовый счет открывается по каждому конкретному расчетному счету клиента.                               "
.
