[Xattr 4.1d] // Экспорт данных произвел SAMI 09/06/2016 10:17:56 БД "-db /home2/bis/quit41d/db/bisquit,-ld bisquit,-Mm 16384,-spin 5000"
"opb" "КонтрАкцепт" no "Контроль Акцепт" "" no "logical" "Да/Нет" "" no no "*" "" no no yes no "с" 0 "" "" 0 "CAN-DO" no no no ""
.
