[User-Proc 4.1d] // Экспорт данных произвел KSBIS 12/08/2015 16:01:02 БД "-db /home2/bis/quit41d/db/bisquit,-ld bisquit,-Mm 16384,-spin 5000"
0 ? "ОТЧЕТЫ ГЕНЕРАТОРА" "Base" 1 "RepGen" 2968 yes "Корневой раздел генератора отчетов" ""
0 "snyatie" "Отчет по снятию в Excel" "base" 2968 "RepGen" 175241 yes "" ""
.
[Reports] // Экспорт данных произвел KSBIS 12/08/2015 16:01:02 БД "-db /home2/bis/quit41d/db/bisquit,-ld bisquit,-Mm 16384,-spin 5000"
"snyatie" 1 "begdate:<#beg-date#> "
"snyatie" 2 "enddate:<#end-date#> "
"snyatie" 3 "custcode:<#custcode#> "
"snyatie" 4 "Procent:<#Procent#>"
"snyatie" 5 "[table]:1"
"snyatie" 6 "<!REPEAT[rep],BEGIN!>"
"snyatie" 7 "<#NumRec[rep]#>"
"snyatie" 8 "<#Custid[rep]#> "
"snyatie" 9 "<#custname[rep]#> "
"snyatie" 10 "<#dates[rep]#>"
"snyatie" 11 "<#numdb[rep]#>"
"snyatie" 12 "<#numct[rep]#>  "
"snyatie" 13 "<#sumdb[rep]#>"
"snyatie" 14 "<#sumct[rep]#>  "
"snyatie" 15 "<#minper[rep]#>"
"snyatie" 16 "<!REPEAT[rep],END!>"
"snyatie" 17 "[table/]:1"
"snyatie" 18 "Itogct:<#Itogct#>  "
"snyatie" 19 "Itogdb:<#Itogdb#>  "
"snyatie" 20 "Itogsumct:<#Itogsumct#>"
"snyatie" 21 "Itogsumdb:<#Itogsumdb#>"
"snyatie" 22 "Itogper:<#Itogper#>  "
.
[Report-Fields] // Экспорт данных произвел KSBIS 12/08/2015 16:01:02 БД "-db /home2/bis/quit41d/db/bisquit,-ld bisquit,-Mm 16384,-spin 5000"
.
[Signs] // Экспорт данных произвел KSBIS 12/08/2015 16:01:02 БД "-db /home2/bis/quit41d/db/bisquit,-ld bisquit,-Mm 16384,-spin 5000"
"ВидДок" "" "175241" "user-proc" "snyatie" ? ?
"ПчтРеж" "" "175241" "user-proc" "XlsVar" ? ?
.
